### ISSUE TITLE
Should fileEq on two files that don't exist return True?

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/extra#17]
Following on from #16, should `fileEq` on two files that don't exist be `True`? I'm inclined to think it should, since then you have the property that `fileEq a a == True`, which seems desirable, and also provides an implementation shortcut if met.

We can change it right now, since I only just released the new version, but I think it has to be today. CC @jacereda

**Comment by jacereda** [comment]
Whatever you prefer,  `copyFileChanged` will just raise the error later if the first file doesn't exist.

**Comment by ndmitchell** [comment]
For `copyFileChanged` it will have already done a `need` so if the first file doesn't exist it will already be an error.

**Comment by ndmitchell** [comment]
I'm not really convinced either way, so if you have a strong preference or even a leaning I'd be very interested.

**Comment by jacereda** [comment]
Not really. In any case, I was thinking that maybe `copyFileChanged` should just attempt the copy via `copyFileWithMetadata`, since that would mean the whole thing could be done on a single pass instead of one for comparing and one for copying. Am I wrong?

**Comment by jacereda** [comment]
Also, a copy based on https://hackage.haskell.org/package/mmap would probably be faster than whatever `copyFile` is doing. But maybe adding that dependency to extra isn't a good idea.

**Comment by ndmitchell** [comment]
The other option is that `fileEq` should compare files that exists, and throw errors if they don't, and so `copyFileChanged` should guard that explicitly. I think might prefer that since its a bit weird to have magic if the file doesn't exist.

As soon as you open the output handle for writing you have lots of issues with modtime changes, so we really want to scan the file first, then copy the file second.

**Comment by jacereda** [comment]
After `copyFileWithMetadata` completes the mtime should be the same as the source. Is the problem that some other thread could be checking the mtime meanwhile?

**Comment by jacereda** [comment]
Hmmm, looks like `copyFile` isn't so great. It calls https://hackage.haskell.org/package/directory-1.2.6.2/docs/src/System.Directory.html#withReplacementFile which will copy first to a temporary location and perform a rename afterwards. If you happen to be building on a separate drive, the file will be copied twice.

**Comment by ndmitchell** [comment]
OK, that probably works then. However, we still can't use it on older versions of GHC - even GHC 7.10 doesn't have it.

**Comment by ndmitchell** [comment]
OK, so we should definitely use copyFileWithMetadata is we have it, and not do anything else. For legacy directory packages we still have to fileEq/copyFile, since we definitely don't want to do our own gunk for the copyFile.

**Comment by jacereda** [comment]
I'll do some experiments with mmap to see if it's worth. Maybe not extra, but shake could depend on some external fast copy library if it can yield a noticeable improvement.

**Comment by ndmitchell** [comment]
I doubt even if it's 5x faster I'd want to move. It introduces an extra dependency which is only used for people doing copies, which is pretty rare. It also means we'd have to do things like metadata moving ourselves, which is a whole can of worms I don't want to get into. Looking at copyFileWithMetadata that definitely seems to be the way to go since it defers to `CopyFile` on Windows, and thus will probably be way smarter/faster than we can do in Haskell.

**Comment by jacereda** [comment]
In my case copies are a big share of the total build. In any case, I can just invoke this hypothetically faster copy from my build system anyways.

**Comment by ndmitchell** [comment]
I'm surprised copy is a big fraction. If you can limit yourself to the latest directory `copyFileWithMetadata` is probably the way to go.

**Comment by jacereda** [comment]
I have to copy a whole python distribution, manuals, images, videos…
I think what hurts more is that there’re lots of small files, so maybe I won’t notice a faster copy that much.
What do you mean by ‘limit yourself to the latest directory’?

**Comment by ndmitchell** [comment]
I mean limit yourself to using the latest directory package. For `copyFileChanged` perhaps you could have a `getModificationTime` check on both sides, and if they are equal skip the reading entirely? I don't think that's a good way to go in general, but if it is a bottleneck for you it might be worth trying.

**Comment by ndmitchell** [comment]
So then plan is:

* Given it's a bottleneck in your code, you should use `copyFileWithMetadata`. In a future GHC version Shake should do the same (I'd happily take a patch now if someone wants to do the necessary CPP logic).
* `fileEq` should throw errors if the files don't both exist - and people can layer whatever semantics for missing files on top. I think that's the only sensible way. I've patched extra, and will make a new release in 10 minutes or so. It is a PVP breaking change, but I'm not going to version it as such on the basis the change was out quickly.

**Comment by ndmitchell** [comment]
Released as extra-1.4.5, so closing this ticket.
