### ISSUE TITLE
Add concatForM to Control.Monad.Extra

### ISSUE THREAD

**Issue by snowleopard** [ndmitchell/extra#20]
The following pattern seems to be extremely ubiquitous: `fmap concat $ forM`. A quick [google search](https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22fmap+concat+%24+forM%22) brings hundreds of matches.

We have `concatMapM` in `Control.Monad.Extra`, so perhaps we could add `concatForM` too? One possible implementation is simply `concatForM = flip concatMapM`. Can send a PR if you like this idea.

**Comment by ndmitchell** [comment]
I like <3. Do note that quite a few files are generated - look at the top of the modules that are generated for descriptions of how to regen.

**Comment by snowleopard** [comment]
Done: #21! I've regenerated `src/Extra.hs` and committed the new version -- hope that's what I was supposed to do.
