### ISSUE TITLE
Use clock package

### ISSUE THREAD

**Issue by Mathnerd314** [ndmitchell/extra#22]
First read http://chrisdone.com/posts/measuring-duration-in-haskell.

Now look at `offsetTime`:
```haskell
-- | Call once to start, then call repeatedly to get the elapsed time since the first
--   call. Values will usually increase, unless the system clock is updated
--   (if you need the guarantee, see 'offsetTimeIncrease').
offsetTime :: IO (IO Seconds)
offsetTime = do
    start <- getCurrentTime
    return $ do
        end <- getCurrentTime
        return $ fromRational $ toRational $ end `diffUTCTime` start
```
This is described as "the naive, inaccurate solution" in the blog post.

The "nice" implementation uses `getTime Monotonic` from the [clock](https://hackage.haskell.org/package/clock-0.7.1.1/docs/System-Clock.html) package, and returns `1e-9 * fromRational (toNanoSecs $ end - start)`.

**Comment by ndmitchell** [comment]
Thanks for the pointer! Agreed, that is a better way to go. Only two initial concerns:

* A new dependency, but it seems quite a small well designed package, and should remove the need for `time` (see #23 for the process of removing that), so not a bad way to go.
* Performance considerations. Running 10M duration calculations, equivalent to 20M time queries, on Windows, I benchmark 2.0s for `getCurrentTime`, 2.4s for `getTime Monotonic` and 1.5s for `getTickCount`. That seems a small but liveable slowdown for better results, and probably also to a higher precision. It was originally 2.6s for `getTime Monotonic`, but I optimised it in https://github.com/corsis/clock/pull/41.

With those concerns answered I've switched over.

**Comment by ndmitchell** [comment]
Fixed in 1.4.11.

**Comment by Mathnerd314** [comment]
You probably should look at `offsetTimeIncrease` as well; maybe it's not as useful anymore and can be deprecated?

**Comment by ndmitchell** [comment]
Already done and in that release :)
