### ISSUE TITLE
sleep test failure

### ISSUE THREAD

**Issue by kirelagin** [ndmitchell/extra#37]
```
do (a,_) <- duration $ sleep 1; return $ a >= 1 && a <= 1.1
*** Failed! Falsifiable (after 1 test):
extra-test: Test failed
CallStack (from HasCallStack):
  error, called at test/TestUtil.hs:47:28 in main:TestUtil
Test suite extra-test: FAIL
```

The test failed two times in a row. The computer is not top notch, but is not terrible either: a rather old iMac with Core i3 550 @ 3.2GHz, but it was under very heavy load (compiling multiple Haskell packages and a couple of GHC versions at the same time). So, maybe, it would not be a bad idea to slightly increase the upper bound just in case...

**Comment by themoritz** [comment]
Also suffering from the same problem while building as part of a highly parallel nix build...

**Comment by ndmitchell** [comment]
Released - let's reopen if it causes problems in future.
