### ISSUE TITLE
extra-1.0 test suite hangs indefinitely when built with GHC 7.10.1-rc1

### ISSUE THREAD

**Issue by peti** [ndmitchell/extra#4]
When I run 'cabal check', the test suite starts up, but it doesn't consume any CPU nor does it ever terminate. This happens only when I build the package with GHC 7.10.1-rc1; the normal 7.8.4 builds succeed just fine.

**Comment by ndmitchell** [comment]
Weird for two reasons. 1, I don't believe cabal check runs the test suite. 2, I already tests with GHC 7.10.1 on Linux and it works fine https://travis-ci.org/ndmitchell/extra/jobs/46446400. I guess you have enhanced cabal check or are running cabal test? If you look at the output of running the test (perhaps manually) how far does it get before pausing?

**Comment by peti** [comment]
Here is the explanation for this phenomenon: https://github.com/haskell/cabal/issues/2398.

**Comment by ndmitchell** [comment]
Thanks for tracking that down @peti
