### ISSUE TITLE
`Data.List.Extra.for` clashes with `Data.Traversable.for`

### ISSUE THREAD

**Issue by martin-drhu-da** [ndmitchell/extra#40]

**Comment by ndmitchell** [comment]
It does, and I don't like it. Options:

1) Do nothing, thus preserving backwards compat for the `extra` library, which is useful.
2) Rename `for` - but there's no good name for it.
3) Delete `for`, with a deprecation warning right now, then remove it in a few months.
4) Have `Data.Traversable` rename to avoid clashing with the extra library. My preference. Also the least likely to happen.

I'm leaning towards 3, but appreciate other opinions.

**Comment by ndmitchell** [comment]
Deprecated in 1.6.13.

**Comment by ndmitchell** [comment]
Removed in 1.7
