### ISSUE TITLE
Split TestGen.hs

### ISSUE THREAD

**Issue by zliu41** [ndmitchell/extra#52]
Currently it is problematic to add, for example, `nubOrd` to `Data.List.NonEmpty.Extra`, because `nubOrd` also exists in `Data.List.Extra`, and they clash in TestGen.hs. One solution is to split TestGen.hs to multiple modules, one per `.Extra` module.

**Comment by ndmitchell** [comment]
Having lots of test generated files would be a lot more work to deal with, check in, update etc. Given the only clashing names are in NonEmpty, and I don't foresee any other clashing names, I would just use `NE.nubOrd` in the test, and adjust the test generator to only import the NonEmpty module qualified as a special case.

**Comment by zliu41** [comment]
Sounds good!
