### ISSUE TITLE
Add applyWhen :: Bool -> (a -> a) -> a -> a

### ISSUE THREAD

**Issue by erikryb** [ndmitchell/extra#63]
Consider adding applyWhen from [here](https://hackage.haskell.org/package/ghc-8.10.1/docs/Util.html#v:applyWhen).

**Comment by ndmitchell** [comment]
That doesn't seem unreasonable. I guess Data.Function.Extra would be the right place?

**Comment by andreasabel** [comment]
Identical function defined at http://hackage.haskell.org/package/Agda-2.6.1/docs/Agda-Utils-Function.html#v:applyWhen. Also defines `applyUnless` and monadic variants.

**Comment by ndmitchell** [comment]
I think I'd stick to just applyWhen for now - the monadic variants look a little weird (they take a monadic argument to a function, which is odd). Patch welcome if someone wants to create Data.Function.Extra with it.

**Comment by georgefst** [comment]
This is [in base](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Function.html#v:applyWhen) now.

**Comment by andreasabel** [comment]
@erikryb Please close.

**Comment by ndmitchell** [comment]
Closing it. Given it's in base, I would be happy to include a patch backporting applyWhen to older versions of GHC in Data.Function.Extra.

**Comment by andreasabel** [comment]
Isn't there `base-compat` for such purposes?

**Comment by ndmitchell** [comment]
Yep, but `extra` also provides some level of base-compat, just not total. Often for things that started in extra library.
