### ISSUE TITLE
`Data.Foldable.Extra` not showing up on Hoogle

### ISSUE THREAD

**Issue by mel-brown** [ndmitchell/extra#68]
I can't seem to find the above module when adding `extra-1.7.7` as a dependency to a project on GHC 8.10.2. Seeing as I wrote that library, I must not have regenerated the files properly when committing. I'm not sure how to do this properly since it was giving me errors when running the `Generate.hs` file both through `cabal` and `ghci`, saying it couldn't find the `clock` module...

**Comment by ndmitchell** [comment]
Hmm. Yes. It seems missing from https://hackage.haskell.org/package/extra too. It should have gone in the .cabal file which would have triggered the generator. Unfortunately, fixing that throws up new errors about duplicate names. I'll fix it :)

**Comment by ndmitchell** [comment]
v1.7.8 is now up with Data.Foldable.Extra in the .cabal file, so should be available. Please shout if it doesn't work.
