### ISSUE TITLE
Add withEnvironment and withModifiedEnvironment

### ISSUE THREAD

**Issue by jneira** [ndmitchell/extra#74]
* From https://hackage.haskell.org/package/mockery-0.3.5/docs/Test-Mockery-Environment.html
* I had to use quite frequently and they are not big but uses bracket to recover the original env
* Not sure if they follow: 

> Most of the functions have trivial implementations. If a beginner couldn't write the function, it probably doesn't belong here. 

* They depends on Prelude funcions (i think base-compat can be replaced with base, given the bounds here)

**Comment by ndmitchell** [comment]
Sounds like a suitable inclusion for extra - patch welcome!
