### ISSUE TITLE
`concatUnzip` is just a special case of folding monoids

### ISSUE THREAD

**Issue by JanPokorny** [ndmitchell/extra#78]
https://github.com/ndmitchell/extra/blob/dffea9e28d7adf9f4dd59236220d0c26f7d28ee4/src/Data/List/Extra.hs#L261

Found this function on Hoogle thanks to a 1HaskellADay challenge. I thought the implementation was clever, but there is actually a much simpler version: https://twitter.com/xgrommx/status/1374497119143223299

Because everything is a monoid, if you're brave enough.

(I don't expect you to take action on this issue, I just found it hilarious enough to share.)

**Comment by ndmitchell** [comment]
So `concatUnzip = fold`? I wonder if that would be faster, since you can potentially fuse out the concat and unzip together, or something... It feels like the version I've implemented might not be optimal. Some rough-and-ready benchmarks would be super interesting

**Comment by JanPokorny** [comment]
@ndmitchell Did some quick testing and it seems to be the same performance.

**Comment by ndmitchell** [comment]
Did you benchmark at both `-O0` and `-O1` - if one is better at one level, that would be the better one to use, even if they match at `-O1`.

If they're basically the same always, I'd happily accept a refactor to use `fold` here - since then if anyone wants to look at the source they might decide to just use `fold` in their library, or the more restrictive variant, but it seems like a more reasonable choice either way.

**Comment by JanPokorny** [comment]
So, for this benchmark:

```haskell
import Control.Arrow
import Data.Foldable

concatUnzip1 :: [([a], [b])] -> ([a], [b])
concatUnzip1 = fold

concatUnzip2 :: [([a], [b])] -> ([a], [b]) 
concatUnzip2 = (concat *** concat) . unzip

largeArray = [([1..x], [x..1000]) | x <- [1..1000]]

main = putStrLn $ show $ concatUnzip1 largeArray
```
(last line changed to `concatUnzip2` respectively)

Ran like this (PowerShell) for every combination:
```powershell
ghc -O0 t1.hs;
(Measure-Command { for ($i=1; $i -le 100; $i++) { ./t1.exe }) }.TotalSeconds
```

<table>
<tr>
	<td> 
	<td> fold
	<td> original
<tr>
	<td> -O0
	<td> 13.714601 s
	<td> 15.5980192 s
<tr>
	<td> -O1
	<td> 13.6284824 s
	<td> 12.8710655 s
<tr>
	<td> -O2
	<td> 13.4536465 s
	<td> 12.8662584 s
</table>

...it seems like the original implementation is slower for `-O0`, but faster for `-O1` and `-O2`. But it's still very close.

**Comment by ndmitchell** [comment]
Thanks for the benchmarking! If we have to pick, faster at -O1 seems better, so let's stick with the original implementation.

Also note that `***` is from `Data.Tuple.Extra`, not `Control.Arrow`. However, given its not recursive, there's no way it has any impact on performance.
