### ISSUE TITLE
proposal to add filesWithExtension

### ISSUE THREAD

**Issue by juhp** [ndmitchell/extra#82]
I would like to suggest adding a couple of small functions to System.Directory.Extra:

```haskell
filesWithExtension :: FilePath -- directory
                   -> String   -- file extension
                   -> IO [FilePath]

fileWithExtension :: FilePath -- directory
                  -> String   -- file extension
                  -> IO (Maybe FilePath)
```
How does that sound?
If it is okay I am happy to open a PR for it.

**Comment by ndmitchell** [comment]
The second one seems redundant - it's easier to do listToMaybe over the first, or whatever is the right policy to reduce many files down to one.

For `filesWithExtension`, what's the benefit over just doing the `listFiles` and a filter? My concern is you often want to list files directly, with recursion, and with recursion avoiding `.` prefixed directories or similar. By the time you have three variants it starts to explode badly in terms of complexity.

**Comment by juhp** [comment]
This an implementation of filesWithExtension:

```haskell
filesWithExtension :: FilePath -> String -> IO [FilePath]
filesWithExtension dir ext =
  filter (ext `isExtensionOf`) <$> listDirectory dir
```
I admit it looks pretty straightword (specially when one remembers to use isExtensionOf).
I think you are right that listFiles probably makes more sense here.

I see your point, though I do find myself using filesWithExtension (and less often fileWithExtension) in various projects: it is a bit less typing. :-)

**Comment by ndmitchell** [comment]
Yeah, I think I'll close this for now, and not add it. But if in 6 months time or so you've needed to use that one a lot, but not any of the other variations with isExtensionOf, it might be worth considering.
