### ISSUE TITLE
Add (!?) function for lists

### ISSUE THREAD

**Issue by Boarders** [ndmitchell/extra#84]
It would be nice for this function:
```haskell
(!?) :: [a] -> Int -> Maybe a
```
to exist in a convenient place. Would you consider adding it to `extra`?

**Comment by Boarders** [comment]
I am happy to make a PR doing this, I just wanted to run it past you first.

**Comment by Boarders** [comment]
I added a PR for this here: https://github.com/ndmitchell/extra/pull/85. If for whatever reason you don't like idea then no worries!

**Comment by ndmitchell** [comment]
Fixed in #85
