### ISSUE TITLE
third3 isn't as lazy as second from Data.Bifunctor

### ISSUE THREAD

**Issue by vmchale** [ndmitchell/extra#98]
Redefining it as

```
    third3 :: (c -> d) -> (a, b, c) -> (a, b, d)
    third3 f ~(a, b, c) = (a, b, f c)
```

would be less confusing in my opinion, as it would not be subtly off compared to `first`, `second` in base!

**Comment by ndmitchell** [comment]
Going point - also true for a bunch more functions. Updated and I'll make a release now.
